---
name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install build
        run: pip install build

      - name: Run build
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@27a0e8a
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
